"""init

Revision ID: 46e8ad21786f
Revises: 
Create Date: 2026-06-26 09:04:40.564964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46e8ad21786f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('detail_header', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity'), 'audit_log', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_type', sa.Enum('CAR', 'SUV', 'JEEP', 'VAN', 'MOTORBIKE', 'SCOOTER', 'THREE_WHEELER', 'PICKUP', 'LORRY', 'TRUCK', 'BUS', 'TRACTOR', 'HEAVY_MACHINERY', 'BICYCLE', 'QUAD_BIKE', 'BOAT', 'OTHER', name='vehicle_type'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('trim', sa.String(length=50), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('NEW', 'USED', 'RECONDITIONED', name='vehicle_condition'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PENDING', 'SOLD', 'EXPIRED', 'REMOVED', name='vehicle_status'), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_city'), 'vehicles', ['city'], unique=False)
    op.create_index(op.f('ix_vehicles_district'), 'vehicles', ['district'], unique=False)
    op.create_index(op.f('ix_vehicles_make'), 'vehicles', ['make'], unique=False)
    op.create_index(op.f('ix_vehicles_model'), 'vehicles', ['model'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_index(op.f('ix_vehicles_year_of_manufacture'), 'vehicles', ['year_of_manufacture'], unique=False)
    op.create_table('vehicle_documents',
    sa.Column('registration_number', sa.String(length=30), nullable=True),
    sa.Column('chassis_number', sa.String(length=50), nullable=True),
    sa.Column('engine_number', sa.String(length=50), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('revenue_license_expiry', sa.Date(), nullable=True),
    sa.Column('emission_test_expiry', sa.Date(), nullable=True),
    sa.Column('license_status', sa.String(length=20), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_table('vehicle_history',
    sa.Column('previous_owners', sa.Integer(), nullable=False),
    sa.Column('had_accidents', sa.Boolean(), nullable=False),
    sa.Column('accident_history', sa.Text(), nullable=True),
    sa.Column('service_history', sa.Text(), nullable=True),
    sa.Column('import_details', sa.Text(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_table('vehicle_media',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='media_type'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_media_vehicle_id'), 'vehicle_media', ['vehicle_id'], unique=False)
    op.create_table('vehicle_pricing',
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('leasing_available', sa.Boolean(), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicle_pricing_price'), 'vehicle_pricing', ['price'], unique=False)
    op.create_table('vehicle_specs',
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('engine_capacity_cc', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', 'CNG', 'LPG', 'PEDAL', 'OTHER', name='fuel_type'), nullable=True),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', 'TIPTRONIC', 'CVT', 'NONE', name='transmission'), nullable=True),
    sa.Column('body_type', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('seating_capacity', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('drivetrain', sa.String(length=20), nullable=True),
    sa.Column('extra_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicle_specs_body_type'), 'vehicle_specs', ['body_type'], unique=False)
    op.create_index(op.f('ix_vehicle_specs_engine_capacity_cc'), 'vehicle_specs', ['engine_capacity_cc'], unique=False)
    op.create_index(op.f('ix_vehicle_specs_fuel_type'), 'vehicle_specs', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_vehicle_specs_mileage'), 'vehicle_specs', ['mileage'], unique=False)
    op.create_index(op.f('ix_vehicle_specs_transmission'), 'vehicle_specs', ['transmission'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_specs_transmission'), table_name='vehicle_specs')
    op.drop_index(op.f('ix_vehicle_specs_mileage'), table_name='vehicle_specs')
    op.drop_index(op.f('ix_vehicle_specs_fuel_type'), table_name='vehicle_specs')
    op.drop_index(op.f('ix_vehicle_specs_engine_capacity_cc'), table_name='vehicle_specs')
    op.drop_index(op.f('ix_vehicle_specs_body_type'), table_name='vehicle_specs')
    op.drop_table('vehicle_specs')
    op.drop_index(op.f('ix_vehicle_pricing_price'), table_name='vehicle_pricing')
    op.drop_table('vehicle_pricing')
    op.drop_index(op.f('ix_vehicle_media_vehicle_id'), table_name='vehicle_media')
    op.drop_table('vehicle_media')
    op.drop_table('vehicle_history')
    op.drop_table('vehicle_documents')
    op.drop_index(op.f('ix_vehicles_year_of_manufacture'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_model'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_make'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_district'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_city'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
